services:
  vinylium.database:
    image: "postgres:18.3-alpine3.23"
    container_name: "vinylium-database"
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    env_file: ./server/db.env
    volumes:
      - pgdata:/var/lib/postgresql/
  
  vinylium.server:
    environment:
      - ASPNETCORE_HTTP_PORTS=1738
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    env_file: ./server/.env
    image: vinylium-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1738:1738"
  
  vinylium.client:
    container_name: "vinylium-client"
    image: vinylium-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - vinylium.server
  
volumes:
    pgdata: